spring:
  profiles:
    active:
      prod
      #dev-mariadb
      #dev-h2
      #test
  jpa:
    show-sql: false

---

spring:
  profiles: test
  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

---

spring:
  profiles: dev-h2
  h2:
    console:
      enabled: true

---

spring:
  profiles: dev-mariadb
  datasource:
    url: jdbc:mariadb://localhost:3306/mhp?serverTimezone=UTC
    username: misrra
    password: misrra
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
  jpa:
    hibernate:
      ddl-auto: none

---

spring:
  profiles: prod
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
